codecov:
  require_ci_to_pass: false
comment: false
coverage:
  status:
    patch: off
ignore:
  - "precompiles"
  - "script"
  - "src/core/libraries/NFTSVG.sol"
  - "src/core/libraries/SVGElements.sol"
  - "test"
