# See https://github.com/sablier-labs/devkit/blob/main/just/evm.just
import "./node_modules/@sablier/devkit/just/evm.just"

# Run just --list to see all available commands
default:
  @just --list

deploy *args:
    FOUNDRY_PROFILE=optimized \
        forge script scripts/solidity/DeployDeterministicFactories.s.sol \
        -vvv --broadcast {{ args }}
  