name: "Deploy NFT Descriptor"

env:
  API_KEY_INFURA: ${{ secrets.API_KEY_INFURA }}
  FOUNDRY_PROFILE: "optimized"
  MNEMONIC: ${{ secrets.MNEMONIC }}

on:
  workflow_dispatch:
    inputs:
      chain:
        default: "sepolia"
        description: "Chain name as defined in the Foundry config."
        required: false

jobs:
  deploy-nft-descriptor:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"
        with:
          submodules: "recursive"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Deploy the NFT Descriptor"
        run: >-
          forge script script/DeployNFTDescriptor.s.sol
          --broadcast
          --rpc-url "${{ inputs.chain }}"
          --verify
          -vvvv

      - name: "Add workflow summary"
        run: |
          echo "## Result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Done" >> $GITHUB_STEP_SUMMARY
