name: "Deploy Lockup Dynamic"

env:
  API_KEY_ETHERSCAN: ${{ secrets.API_KEY_ETHERSCAN }}
  API_KEY_INFURA: ${{ secrets.API_KEY_INFURA }}
  FOUNDRY_PROFILE: "optimized"
  MNEMONIC: ${{ secrets.MNEMONIC }}

on:
  workflow_dispatch:
    inputs:
      admin:
        default: "0x0E109f35926575FC64Ec73735101966d434Ed591"
        description: "Initial contract admin."
        required: false
      chain:
        default: "goerli"
        description: "Chain name as defined in the Foundry config."
        required: false
      comptroller:
        description: "Address of an already deployed comptroller."
        required: true
      nft-descriptor:
        description: "Address of an NFT descriptor contract."
        required: true
      max-segment-count:
        default: "300"
        description: "Maximum number of segments allowed in a stream."
        required: false

jobs:
  deploy-lockup-dynamic:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Deploy the SablierV2LockupDynamic contract"
        run: >-
          forge script script/DeployLockupDynamic.s.sol
          --broadcast
          --rpc-url "${{ inputs.chain }}"
          --sig "run(address,address,address,uint256)"
          "${{ inputs.admin }}"
          "${{ inputs.comptroller }}"
          "${{ inputs.nft-descriptor }}"
          "${{ inputs.max-segment-count }}"
          -vvvv

      - name: "Add workflow summary"
        run: |
          echo "## Result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Done" >> $GITHUB_STEP_SUMMARY
